name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
      - run: |
          npm install
          cd frontend
          npm install --legacy-peer-deps
          npm run build
          cd ..
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
